version: '3.8'
services:

  proxy:
    image: nginx:1.18.0-alpine
    #image: nginx:mainline
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  webapi:
    build: .\webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
